/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Appointment = IDL.Record({
  'service' : IDL.Text,
  'date' : IDL.Text,
  'name' : IDL.Text,
  'timestamp' : IDL.Int,
  'phone' : IDL.Text,
});
export const ContactForm = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : IDL.Int,
});

export const idlService = IDL.Service({
  'bookAppointment' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'getAllAppointments' : IDL.Func([], [IDL.Vec(Appointment)], ['query']),
  'getAllContactForms' : IDL.Func([], [IDL.Vec(ContactForm)], ['query']),
  'getAppointmentByPhone' : IDL.Func([IDL.Text], [Appointment], ['query']),
  'submitContactForm' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Appointment = IDL.Record({
    'service' : IDL.Text,
    'date' : IDL.Text,
    'name' : IDL.Text,
    'timestamp' : IDL.Int,
    'phone' : IDL.Text,
  });
  const ContactForm = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : IDL.Int,
  });
  
  return IDL.Service({
    'bookAppointment' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'getAllAppointments' : IDL.Func([], [IDL.Vec(Appointment)], ['query']),
    'getAllContactForms' : IDL.Func([], [IDL.Vec(ContactForm)], ['query']),
    'getAppointmentByPhone' : IDL.Func([IDL.Text], [Appointment], ['query']),
    'submitContactForm' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };